RiskRegisterII/Controllers/ErrorRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RiskRegister.Models;
using RiskRegisterII.Models;
using RiskRegisterII.Models.ViewModels;
using RiskRegisterII.Services;

namespace RiskRegisterII.Controllers
{
    [Route("ErrorRegister/[controller]")]
    public class ErrorRegisterController : Controller
    {

        private readonly IErrorRegister _errorRegister;
        private readonly IDepartment _department;
        private readonly ICompany _company;
        private readonly IRiskType _riskType;
        private readonly IUserManager _userManager;

        public ErrorRegisterController(IErrorRegister errorRegister, IDepartment department, ICompany company, IRiskType riskType, IUserManager userManager)
        {
            _errorRegister = errorRegister; _company = company; _department = department; _riskType = riskType; _userManager = userManager;

        }

        // [Route("/ErrorRegister")]
        // GET: ErrorRegister
        public ActionResult Index()
        {

            var userId = User.Identity.Name;
          
            //var loggedInUser = _appUserService.GetAppUser(t => t.Id == userId).FirstOrDefault();

            var _returnRegisters = _errorRegister.AllErrorRegisters();
            var _companyList = _company.AllCompanies();
            var _departmentList = _department.AllDepartments();
            var _riskList = _riskType.AllRiskTypes();

            var query = from errors in _returnRegisters
                        join companylist in _companyList on errors.CompanyId equals companylist.Id
                        join departmentlist in _departmentList on errors.DepartmentId equals departmentlist.Id
                        join risklist in _riskList on errors.RiskTypeId equals risklist.Id
                        select new ErrorRegisterVM
                        {
                            Id = errors.Id,
                            DateCreated = errors.DateCreated,
                            ErrorType = errors.ErrorType,
                            Narration = errors.Narration,
                            Officer = errors.Officer,
                            Status = errors.Status,
                            ErrorStatus = errors.ErrorStatus,
                            Remark = errors.Remark,
                            RiskType = risklist.Name,
                            Company = companylist.Name,
                            Department = departmentlist.Name,
                            DateUpdated = errors.DateUpdated,
                            UpdatedBy = userId

                        };

            return View(query);
        }

        // GET: ErrorRegister/Details/5
        [Route("/ErrorRegister/Details/{id}")]
        public ActionResult Details(int id)
        {
            var _getErrorRegisters = _errorRegister.GetErrorRegister(id);
            return View(_getErrorRegisters);
        }

        // GET: ErrorRegister/Create
        [Route("/ErrorRegister/Create")]
        public ActionResult Create()
        {
            List<Company> companyList = new List<Company>();
            List<Department> departmentlist = new List<Department>();
            List<RiskType> riskTypeList = new List<RiskType>();

            companyList = _company.AllCompanies().ToList();
            companyList.Insert(0, new Company { Id = 0, Name = "Select" });

            departmentlist = _department.AllDepartments().ToList();
            departmentlist.Insert(0, new Department { Id = 0, Name = "Select"});

            riskTypeList = _riskType.AllRiskTypes().ToList();
            riskTypeList.Insert(0, new RiskType { Id=0, Name = "Select"});

            ViewBag.CompanyDetails = companyList;
            ViewBag.DepartmentDetails = departmentlist;
            ViewBag.RiskTypeDetails = riskTypeList;




            return View();
        }

        // POST: ErrorRegister/Create
        [HttpPost]
        [Route("/ErrorRegister/Create")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ErrorRegisterModel errorRegister, IFormCollection collection)
        {
            try
            {
                
                // TODO: Add insert logic here
                _errorRegister.AddErrorRegister(errorRegister);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ErrorRegister/Edit/5
         [Route("/ErrorRegister/Edit/{id}")]
        public ActionResult Edit(int id)
        {
            List<Company> companyList = new List<Company>();
            List<Department> departmentlist = new List<Department>();
            List<RiskType> riskTypeList = new List<RiskType>();

            companyList = _company.AllCompanies().ToList();
            companyList.Insert(0, new Company { Id = 0, Name = "Select" });

            departmentlist = _department.AllDepartments().ToList();
            departmentlist.Insert(0, new Department { Id = 0, Name = "Select" });

            riskTypeList = _riskType.AllRiskTypes().ToList();
            riskTypeList.Insert(0, new RiskType { Id = 0, Name = "Select" });

            ViewBag.CompanyDetails = companyList;
            ViewBag.DepartmentDetails = departmentlist;
            ViewBag.RiskTypeDetails = riskTypeList;

            var _getErrorRegisters = _errorRegister.GetErrorRegister(id);
            return View(_getErrorRegisters);
        }

        // POST: ErrorRegister/Edit/5
        [HttpPost]
        [Route("/ErrorRegister/Edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Save(int id, ErrorRegisterModel errorRegister, IFormCollection collection)
        {
            try
            {         
                // TODO: Add update logic here
                _errorRegister.UpdateErrorRegister(id, errorRegister);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ErrorRegister/Delete/5
        [Route("/ErrorRegister/Delete/{id}")]
        public ActionResult Delete(int id)
        {
            var _getErrorRegisters = _errorRegister.GetErrorRegister(id);
            return View(_getErrorRegisters);
        }

        // POST: ErrorRegister/Delete/5
        [HttpPost]
        [Route("/ErrorRegister/Delete/{Id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _errorRegister.DeleteErrorRegister(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

RiskRegisterII/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using RiskRegister.Models;
using RiskRegisterII.Data;
using RiskRegisterII.Models;
using RiskRegisterII.Services;

namespace RiskRegister.Controllers
{
    public class HomeController : Controller
    {

        private readonly IUserManager _userManager;
        private readonly IErrorRegister _errorRegister;
        private readonly IDepartment _department;
        private readonly ICompany _company;
        private readonly IRiskType _riskType;
        private readonly IRegisterRisk _registerRisk;
        private readonly IComplaintRegister _complaintRegister;

        public HomeController(IUserManager userManager, IErrorRegister errorRegister, 
            IDepartment department, ICompany company, IRiskType riskType, IRegisterRisk registerRisk, 
            IComplaintRegister complaintRegister)
        {
            _userManager = userManager;
            _errorRegister = errorRegister;
            _department = department;
            _company = company;
            _riskType = riskType;
            _registerRisk = registerRisk;
            _complaintRegister = complaintRegister;
        }


        //[ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Entry()
        {
            // view bag values for the front end 
            ViewBag.CompanyCount = _company.AllCompanies().Count();
            ViewBag.DepartmentCount = _department.AllDepartments().Count();
            ViewBag.RiskTypeCount = _riskType.AllRiskTypes().Count();
            ViewBag.RegisteredRisks = _registerRisk.AllRiskRegisters().Count();

            return View();
        }


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            var isValid = _userManager.Authenticate(loginModel.Email, loginModel.Password);

            if (!isValid)
            {
                ModelState.AddModelError("", "Invalid username and /or password");
                return View();
            }

            var user = _userManager.GetUser(loginModel.Email);
            var userDetail = _userManager.GetUserDetailByUserID(user.ID);
            var roles = _userManager.GetUserRoles(user.ID);
            // get user profile details 

            List<Claim> claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, (userDetail?.Lastname + " " +((userDetail?.FirstName!="")? userDetail.FirstName[0]+ ".": "") + ((userDetail?.MiddleName!="")? userDetail.MiddleName[0] + ".": "") )),
                new Claim(ClaimTypes.Email, ((userDetail?.Email!=null)?userDetail.Email:user.Username)),
                new Claim("USERNAME", user.Username),
                new Claim("ID", user.ID.ToString()),
                new Claim(ClaimTypes.Role, roles.FirstOrDefault().Name),

            };
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "cookie");
            ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

            // Sign in
            await HttpContext.SignInAsync(
                scheme: "RiskManagement", 
                principal: claimsPrincipal);

            if (claimsPrincipal.IsInRole("SuperAdmin"))
            {
                return RedirectToAction("Entry", "Home");
            }
            else
            {
              return RedirectToAction("Index", "ErrorRegister");
            }

        }

        public IActionResult AccessDenied()
        {
            return View();
        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(scheme: "RiskManagement");
            return View("index");
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

RiskRegisterII/Controllers/RegisterRiskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

using RiskRegister.Models;
using RiskRegisterII.Data;
using RiskRegisterII.Models;
using RiskRegisterII.Models.ViewModels;
using RiskRegisterII.Services;

namespace RiskRegisterII.Controllers
{
    public class RegisterRiskController : Controller
    {
        // the grand opener
        private readonly RiskRegisterDbContext riskRegisterDbContext;
        // ends here

        private readonly IErrorRegister _errorRegister;
        private readonly IDepartment _department;
        private readonly ICompany _company;
        private readonly IRiskType _riskType;
        private readonly IRegisterRisk _registerRisk;
        private readonly IComplaintRegister _complaintRegister;


        public RegisterRiskController(RiskRegisterDbContext _riskRegisterDbContext, IErrorRegister errorRegister, IDepartment department,
            ICompany company, IRiskType riskType, IRegisterRisk registerRisk, IComplaintRegister complaintRegister)
        {
            riskRegisterDbContext = _riskRegisterDbContext;

            _errorRegister = errorRegister;
            _department = department;
            _company = company;
            _riskType = riskType;
            _registerRisk = registerRisk;
            _complaintRegister = complaintRegister;

        }

        
        // GET: RegisterRisk
        public ActionResult Index(string searchValue, int? page)
        {
            var model = from records in riskRegisterDbContext.RiskRegisters
                        select records;
     

            if (!string.IsNullOrEmpty(searchValue))
            {
                model = model.Where(c => c.RiskName.Contains(searchValue));
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);

            return View(model.ToPagedList(pageNumber, pageSize));
           
        }



        //[AllowAnonymous]
        public IActionResult TestDB()
        {
            var testresult = _registerRisk.AllRiskRegisters();
            return View(testresult);
        }


        // GET: RegisterRisk/Details/5
        [Authorize(Roles ="SuperAdmin")]
        public ActionResult Details(int id)
        {
            //var _registerRisks = _registerRisk.AllRiskRegisters();
            var _riskTypes = _riskType.AllRiskTypes();

            var _result = _registerRisk.GetRiskRegister(id);
            var _returnView = _riskType.AllRiskTypes().Where(t => t.Id == _result.RiskTypeId).FirstOrDefault();

            var registerVM = new RegisterRiskVM()
            {
                Id = _result.Id,
                Activity = _result.Activity,
                InherentRisk = _result.InherentRisk,
                LoggedBy = _result.LoggedBy,
                RiskTypeName = _returnView.Name,
                Mitigants = _result.Mitigants,
                DateCreated = _result.DateCreated
            };

            return View(registerVM);
        }

        // GET: RegisterRisk/Create
        public ActionResult Create()
        {
            List<RiskType> riskTypeList = new List<RiskType>();
            riskTypeList = _riskType.AllRiskTypes().ToList();
            riskTypeList.Insert(0, new RiskType {  Name = "Select" });

            ViewBag.RiskLists = riskTypeList;

            return View();
        }

        // POST: RegisterRisk/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RegisterRisk registerRisk, IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                _registerRisk.AddRiskRegister(registerRisk);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RegisterRisk/Edit/5
        public ActionResult Edit(int id)
        {
            List<RiskType> riskTypeList = new List<RiskType>();

            riskTypeList = _riskType.AllRiskTypes().ToList();
            riskTypeList.Insert(0, new RiskType { Id = 0, Name = "Select" });

            ViewBag.RiskTypeDetails = riskTypeList;

            var _getRegister = _registerRisk.GetRiskRegister(id);
            return View(_getRegister);
        }

        // POST: RegisterRisk/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, RegisterRisk register, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                _registerRisk.UpdateRiskRegister(id, register);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RegisterRisk/Delete/5
        public ActionResult Delete(int id)
        {
            var _riskTypes = _riskType.AllRiskTypes();

            var _result = _registerRisk.GetRiskRegister(id);
            var _returnView = _riskType.AllRiskTypes().Where(t => t.Id == _result.RiskTypeId).FirstOrDefault();

            var registerVM = new RegisterRiskVM()
            {
                Id = _result.Id,
                Activity = _result.Activity,
                InherentRisk = _result.InherentRisk,
                LoggedBy = _result.LoggedBy,
                RiskTypeName = _returnView.Name,
                Mitigants = _result.Mitigants,
                DateCreated = _result.DateCreated
            };

            return View(registerVM);
        }

        // POST: RegisterRisk/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                 _registerRisk.DeleteRiskRegister(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

RiskRegisterII/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

RiskRegisterII/Views/Home/AccessDenied.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AccessDenied</title>
    <style>
        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
        }
    </style>
</head>
<body>
    <div class="container center" >
        <img src="~/images/accessdeniedIII.jpeg" />
    </div>

</body>
</html>

RiskRegisterII/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RiskRegisterII/Views/Home/Entry.cshtml
@{
    ViewData["Title"] = "Entry";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


<div class="pull-right" >
    <img src="~/images/user.png" width="30" height="30" /> @User.Identity.Name
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    @*<p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It's built with default Bootstrap components and utilities with little customization.</p>*@
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon" style="background-color: #00c0ef">
                    <i class="ion ion-ios-pulse" style="color:#fff"></i>
                </span>
                <div class="info-box-content">
                    <br />
                    <span class="info-box-text" style="margin:15px"> Risk Types</span><br />
                    <span class="info-box-number" style="margin:15px">@ViewBag.RiskTypeCount</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon" style="background-color: #84d46c">
                    <i class="ion ion-ios-keypad" style="color:#fff"></i>
                </span>
                <div class="info-box-content">
                    <br />
                    <span class="info-box-text" style="margin:15px"> Companies</span><br />
                    <span class="info-box-number" style="margin:15px">@ViewBag.CompanyCount</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon" style="background-color: #dd4b39">

                    <i class="ion ion-ios-settings" style="color:#fff"></i>
                </span>
                <div class="info-box-content">
                    <br />
                    <span class="info-box-text" style="margin:15px">Departments</span><br />
                    <span class="info-box-number" style="margin:15px">@ViewBag.DepartmentCount</span>
                </div>
   
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon" style="background-color: #f39c12">
                    <i class="ion ion-ios-people-outline" style="color:#fff"></i>
                </span>
                <div class="info-box-content">
                    <br />
                    <span class="info-box-text" style="margin:15px">Registered Risks</span><br />
                    <span class="info-box-number" style="margin:15px">@ViewBag.RegisteredRisks </span>
                </div>
                <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
        </div>
    </div>
    <br /><br />

    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal"></h4>
            </div>
            <div class="card-body">
                <br />
                <img src="~/images/risk3.png" style="width: 100px; height:100px" />
                <br />    <br />
                <a class="btn btn-lg btn-block btn-outline-success" asp-controller="RegisterRisk" asp-action="Index">Risks</a>
                <br />    <br />
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal"></h4>
            </div>
            <div class="card-body">
                <br />
                <img src="~/images/error.png" style="width: 100px; height:100px" />
                <br />    <br />
                <a class="btn btn-lg btn-block btn-outline-success" asp-controller="ErrorRegister" asp-action="Index">Errors</a>
                <br />    <br />
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal"></h4>
            </div>
            <div class="card-body">
                <br />
                <img src="~/images/totalcomplaints.png" style="width: 100px; height:100px" />
                <br />    <br />

                <a class="btn btn-lg btn-block btn-outline-success" asp-controller="ComplaintRegister" asp-action="Index">Complaints</a>
                <br />    <br />
            </div>
        </div>
    </div>

</div>

RiskRegisterII/Views/Home/Index.cshtml
@model RiskRegisterII.Models.LoginModel
@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}
<br />

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Risk Management</title>
    <script type="text/javascript">
        function preventBack() { window.history.forward(); }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };
    </script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @*<environment include="Development">

        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>*@
</head>
<body >
    <br />
    <br />
    <div class="container body-content text-center">
        <div class="img-responsive input-group center-block">
            <img src="~/images/parthianlogo2.png" />
            @*<img src="~/images/psllogo.png" />*@
            @*<h1 class="h3 mb-3 font-weight-normal">Risk Register</h1><br />*@
        </div>

        <form class="form-signin">
            
            @*<label for="inputEmail" class="sr-only">Email address</label>*@
            @*<input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus @Html.EditorFor(model => model.EmailAddress)>*@

            <div class="form-group">
                @*<label asp-for="EmailAddress" class="control-label"></label>*@
                <input asp-for="Email" class="form-control" placeholder="Email Address" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>


            <div class="form-group">
                @*<label asp-for="EmailAddress" class="control-label"></label>*@
                <input type="password" asp-for="Password" class="form-control" placeholder="Password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <br />
            @*<div class="checkbox mb-3">
                    <label>
                        <input type="checkbox" value="remember-me"> Remember me
                    </label>
                </div>*@
            <button class="btn btn-lg btn-primary btn-block" type="submit" asp-controller="Home" asp-action="Login">Sign in</button>
            @*<p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>*@
            <br/>
            @*<a class="btn btn-outline-danger" asp-controller="" asp-action="">Register</a>*@
        </form>

        <br />    <br />

        <hr />
        <footer>
            <p style="color: #b6a423">&nbsp;&nbsp;&copy; 2018 - PARTHIAN GROUP |<b style="color:teal"> Risk Register.</b></p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*<environment include="Development">

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>*@



</body>
</html>